# vim: set ft=Dockerfile:

FROM spikeekips/golang

COPY ./modules.go $GOPATH/src/modules.go
COPY . $GOPATH/src/github.com/gliderlabs/resolvable
COPY ./build.sh /build.sh

ENV GO_EXTLINK_ENABLED=0
ENV CGO_ENABLED=0

WORKDIR ${GOPATH}/src/github.com/gliderlabs/resolvable
RUN go get
RUN go build -x --ldflags "-extldflags '-static' -X main.Version=$1" -o /resolvable
